<a href="https://colab.research.google.com/github/Ayush-hm/Machine-Learning/blob/main/NNfromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# prompt: code for getting mnist dataset

from keras.datasets import mnist
(train_X, train_y), (test_X, test_y) = mnist.load_data()


11490434/11490434 [==============================] - 0s 0us/step


In [4]:
train_X

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [9]:
train_X.shape

(60000, 28, 28)

In [11]:
train_y.shape

(60000,)

In [12]:
test_X.shape

(10000, 28, 28)

In [13]:
test_y.shape

(10000,)

In [14]:
import numpy as np

In [26]:
def initparams():
  W1=np.random.rand(10,784) - 0.5
  b1=np.random.rand(10,1) - 0.5
  # why are we subtracting 0.5?
  W2=np.random.rand(10,10) - 0.5
  b2=np.random.rand(10,1) - 0.5
  return W1, b1, W2, b2

In [27]:
def ReLU(z):
  return np.maximum(0,z)

In [28]:
def softmax(z):
  return np.exp(z)/np.sum(np.exp(z), axis=0)

In [42]:
def forwprop(W1,W2,b1,b2,X):
  X=X.reshape(X.shape[0],-1).T
  Z1 = W1.dot(X) + b1
  A1 = ReLU(Z1)
  Z2 = W2.dot(A1) + b2
  A2=softmax(A1)
  return Z1, A1, Z2, A2

In [30]:
def onehot(y):
  one_hot_y = np.zeros((y.size,y.max()+1))
  one_hot_y[np.arange(y.size),y] = 1
  one_hot_y = one_hot_y.T
  return one_hot_y

In [31]:
def deriv_ReLU(x):
  x[x<=0] = 0
  x[x>0] = 1
  return x

In [55]:
def backprop(Z1, A1, Z2, A2, W1, W2, X, Y):
    m=Y.size
    one_hot_Y = onehot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    X_reshaped= X.reshape(X.shape[0],-1).T
    dW1 = 1 / m * dZ1.dot(X_reshaped.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

In [33]:
def update_params(W1,b1,W2,b2,dW1,dW2,db1,db2,alpha):
  W1=W1-alpha*dW1
  b1=b1-alpha*db1
  W2=W2-alpha*dW2
  b2=b2-alpha*db2
  return W1,b1,W2,b2

In [34]:
def get_predictions(A2):
  return np.argmax(A2,0)

In [35]:
def get_accuracy(preds, Y):
  print(preds, Y)
  return np.sum(preds==Y)/Y.size

In [53]:
def gradient_descent(X,Y,alpha,iters):
  W1,b1,W2,b2 = initparams()
  for i in range(iters):
    Z1,A1,Z2,A2 = forwprop(W1,W2,b1,b2,X)
    dW1,db1,dW2,db2 = backprop(Z1,A1,Z2,A2,W1,W2,X,Y)
    W1,b1,W2,b2 = update_params(W1,b1,W2,b2,dW1,dW2,db1,db2,alpha)
    if (i%10 == 0):
      print("Iteration: ", i)
      print("Accuracy: ", get_accuracy(get_predictions(A2),Y))
  return W1,b1,W2,b2

In [56]:
W1, b1, W2, b2 = gradient_descent(train_X,train_y,0.1,500)

<ipython-input-28-620d91fac4e3>:2: RuntimeWarning: overflow encountered in exp
  return np.exp(z)/np.sum(np.exp(z), axis=0)
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
<ipython-input-28-620d91fac4e3>:2: RuntimeWarning: invalid value encountered in divide
  return np.exp(z)/np.sum(np.exp(z), axis=0)


Iteration:  0
[5 1 2 ... 1 2 1] [5 0 4 ... 5 6 8]
Accuracy:  0.06371666666666667
Iteration:  10
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy:  0.09871666666666666
Iteration:  20
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy:  0.09871666666666666
Iteration:  30
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy:  0.09871666666666666
Iteration:  40
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy:  0.09871666666666666
Iteration:  50
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy:  0.09871666666666666
Iteration:  60
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy:  0.09871666666666666
Iteration:  70
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy:  0.09871666666666666
Iteration:  80
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy:  0.09871666666666666
Iteration:  90
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy:  0.09871666666666666
Iteration:  100
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy:  0.09871666666666666
Iteration:  110
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy:  0.09871666666666666
Iteration:  120

In [57]:
import matplotlib.pyplot as plt
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forwprop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = train_X[:, index, None]
    prediction = make_predictions(train_X[:, index, None], W1, b1, W2, b2)
    label = train_y[index]
    print("Prediction: ", prediction)
    print("Label: ", label)

    current_image = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()