<a href="https://colab.research.google.com/github/Ayush-hm/AI-Toolbox/blob/main/Time_Series_Forecasting_using_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

In [2]:
import numpy as np

In [3]:
list=[1,2,3,4]
np.array(list)

array([1, 2, 3, 4])

In [4]:
list =[[1,2,3],[4,5,6],[7,8,9]]
matrix=np.array(list)

In [5]:
print(np.arange(0,10))
print(np.arange(0,10,2))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [6]:
print(np.zeros(5))
print(np.ones(5))
print(np.zeros((3,2)))
print(np.ones((2,3)))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
print(np.ones((4,5)))
print(np.ones((4,5)) + 3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]


In [8]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.random.rand(5,6)

array([[0.98427032, 0.95686182, 0.58195707, 0.45972285, 0.70197216,
        0.1341315 ],
       [0.43747144, 0.63849757, 0.7931625 , 0.68013446, 0.17021678,
        0.3553769 ],
       [0.25124249, 0.97952583, 0.05961634, 0.5169622 , 0.53546033,
        0.16641852],
       [0.63399242, 0.67905198, 0.49782385, 0.68286401, 0.2244749 ,
        0.83689816],
       [0.31581879, 0.6758074 , 0.9796443 , 0.17536363, 0.1711623 ,
        0.42464212]])

In [11]:
np.random.logseries(0.5, 4)

array([1, 1, 1, 1])

In [12]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [13]:
arr=np.arange(25)
rarr=np.random.randint(0,50,10)
print(arr)
print(rarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[41 48 32 20 22 22 10 21 27 28]


In [14]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
print(rarr.max())
print(rarr.min())
print("index of max number",rarr.argmax())
print("index of min number",rarr.argmin())

48
10
index of max number 1
index of min number 6


In [16]:
rarr.dtype

dtype('int64')

In [17]:
arr=np.arange(0,11)
print(arr[1:5])
print(arr[:5])
print(arr[5:])

[1 2 3 4]
[0 1 2 3 4]
[ 5  6  7  8  9 10]


In [18]:
arr + 200

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210])

In [19]:
arr / 3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ,
       3.33333333])

In [20]:
slice_arr=arr[0:6]
slice_arr[:]=10
slice_arr

array([10, 10, 10, 10, 10, 10])

In [21]:
arr_copy=arr.copy()
arr_copy[:]=40
arr_copy

array([40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40])

In [22]:
arr

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [23]:
arr_2d=np.array([[10,22,33],[43,56,65],[72,83,90]])
print(arr_2d)
print(arr_2d[0][1])
print(arr_2d[2,2])

[[10 22 33]
 [43 56 65]
 [72 83 90]]
22
90


In [24]:
slice_2d=arr_2d[:2,0:]
slice_2d

array([[10, 22, 33],
       [43, 56, 65]])

In [25]:
arr=np.arange(1,11)
bool_arr=arr > 5
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [26]:
arr[arr>=5]

array([ 5,  6,  7,  8,  9, 10])

In [27]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [29]:
arr // 2


array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [30]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [31]:
(arr + 4)/2

array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ])

In [32]:
arr/0

/tmp/ipython-input-4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [33]:
arr*(arr**2)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [34]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [35]:
np.cbrt(arr)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382, 2.15443469])

In [36]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [37]:
arr=np.sin(arr)

In [38]:
np.abs(arr)

array([0.84147098, 0.90929743, 0.14112001, 0.7568025 , 0.95892427,
       0.2794155 , 0.6569866 , 0.98935825, 0.41211849, 0.54402111])

In [39]:
arr.sum()

np.float64(1.4111883712180104)

In [40]:
arr.mean()

np.float64(0.14111883712180104)

In [41]:
arr.max()

np.float64(0.9893582466233818)

In [42]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d.sum(axis=1)) #row
print(arr_2d.sum(axis=0)) #column

[ 6 15 24]
[12 15 18]


**Pandas**

In [43]:
import pandas as pd

In [44]:
pd.array(np.array([1,2,3,4]))

<IntegerArray>
[1, 2, 3, 4]
Length: 4, dtype: Int64

In [45]:
labels=['a','b','c']
data=[10,20,30]
arr=np.array(data)
arr

array([10, 20, 30])

In [46]:
d={'a':10,'b':20,'c':30}
pd.Series(data=data)

0    10
1    20
2    30
dtype: int64

In [47]:
pd.Series(data,labels)

a    10
b    20
c    30
dtype: int64

In [48]:
ww1=pd.Series([1,2,3,4],index=['USA','Germany','USSR','Japan'])
ww1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [49]:
ww1['Germany']

np.int64(2)

In [50]:
ww2=pd.Series([7,8,9,0],index=['USA','Germany','Italy','Japan'])
ww2

USA        7
Germany    8
Italy      9
Japan      0
dtype: int64

In [51]:
ww1 + ww2

Germany    10.0
Italy       NaN
Japan       4.0
USA         8.0
USSR        NaN
dtype: float64

In [52]:
pd.DataFrame(np.round(np.random.rand(5,3)*3000),index='NewYork LosAngeles Chicago Houston Philadelphia'.split(),columns='Population Size YearNo.'.split())

Population    Size  YearNo.
NewYork            922.0  2397.0     68.0
LosAngeles        1941.0  2306.0   2678.0
Chicago           2474.0  1689.0    619.0
Houston           1557.0   639.0   2114.0
Philadelphia      1915.0  2158.0   2190.0

In [53]:
from numpy.random import randn
np.random.seed(101)

rand_mat=randn(5,4)
rand_mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [54]:
pd.DataFrame(rand_mat,index='A B C D E'.split(),columns='W X Y Z'.split())

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [55]:
df=pd.DataFrame(data=rand_mat)
df[0:3]

0         1         2         3
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001

In [56]:
df[3]

0    0.503826
1    0.605965
2   -0.589001
3    0.955057
4    0.683509
Name: 3, dtype: float64

In [57]:
df.apply(np.sqrt,axis=0)

0         1         2         3
0  1.645251  0.792548  0.952874  0.709807
1  0.806919       NaN       NaN  0.778438
2       NaN  0.860303  0.727196       NaN
3  0.434391       NaN       NaN  0.977270
4  0.436800  1.406683  1.614301  0.826746

In [58]:
df['4']=df[1]+df[2]
df

0         1         2         3         4
0  2.706850  0.628133  0.907969  0.503826  1.536102
1  0.651118 -0.319318 -0.848077  0.605965 -1.167395
2 -2.018168  0.740122  0.528813 -0.589001  1.268936
3  0.188695 -0.758872 -0.933237  0.955057 -1.692109
4  0.190794  1.978757  2.605967  0.683509  4.584725

In [59]:
df.drop(3,axis=1)

0         1         2         4
0  2.706850  0.628133  0.907969  1.536102
1  0.651118 -0.319318 -0.848077 -1.167395
2 -2.018168  0.740122  0.528813  1.268936
3  0.188695 -0.758872 -0.933237 -1.692109
4  0.190794  1.978757  2.605967  4.584725

In [60]:
df.drop(3)

0         1         2         3         4
0  2.706850  0.628133  0.907969  0.503826  1.536102
1  0.651118 -0.319318 -0.848077  0.605965 -1.167395
2 -2.018168  0.740122  0.528813 -0.589001  1.268936
4  0.190794  1.978757  2.605967  0.683509  4.584725

In [61]:
df.loc[0]

0    2.706850
1    0.628133
2    0.907969
3    0.503826
4    1.536102
Name: 0, dtype: float64

In [62]:
df.iloc[2]

0   -2.018168
1    0.740122
2    0.528813
3   -0.589001
4    1.268936
Name: 2, dtype: float64

In [63]:
df.loc[[2,3]][1]

2    0.740122
3   -0.758872
Name: 1, dtype: float64

In [64]:
df.describe()

0         1         2         3         4
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871  0.906052
std    1.681131  1.061385  1.454516  0.594708  2.505539
min   -2.018168 -0.758872 -0.933237 -0.589001 -1.692109
25%    0.188695 -0.319318 -0.848077  0.503826 -1.167395
50%    0.190794  0.628133  0.528813  0.605965  1.268936
75%    0.651118  0.740122  0.907969  0.683509  1.536102
max    2.706850  1.978757  2.605967  0.955057  4.584725

In [65]:
df[df<=2]

0         1         2         3         4
0       NaN  0.628133  0.907969  0.503826  1.536102
1  0.651118 -0.319318 -0.848077  0.605965 -1.167395
2 -2.018168  0.740122  0.528813 -0.589001  1.268936
3  0.188695 -0.758872 -0.933237  0.955057 -1.692109
4  0.190794  1.978757       NaN  0.683509       NaN

In [66]:
df.columns = 'V W X Y Z'.split()
df

V         W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826  1.536102
1  0.651118 -0.319318 -0.848077  0.605965 -1.167395
2 -2.018168  0.740122  0.528813 -0.589001  1.268936
3  0.188695 -0.758872 -0.933237  0.955057 -1.692109
4  0.190794  1.978757  2.605967  0.683509  4.584725

In [72]:
df[df['V']>0]['Y']

0    0.503826
1    0.605965
3    0.955057
4    0.683509
Name: Y, dtype: float64

In [76]:
df[df['V']>0]['Y'].loc[3]

np.float64(0.9550565092637361)

In [83]:
cond1 = df['W']>0
cond2 = df['Y']<2
df[cond1 & cond2]

V         W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826  1.536102
2 -2.018168  0.740122  0.528813 -0.589001  1.268936
4  0.190794  1.978757  2.605967  0.683509  4.584725

In [84]:
df.reset_index()

index         V         W         X         Y         Z
0      0  2.706850  0.628133  0.907969  0.503826  1.536102
1      1  0.651118 -0.319318 -0.848077  0.605965 -1.167395
2      2 -2.018168  0.740122  0.528813 -0.589001  1.268936
3      3  0.188695 -0.758872 -0.933237  0.955057 -1.692109
4      4  0.190794  1.978757  2.605967  0.683509  4.584725

In [87]:
new_ind= 'CA NY OR LA CO'.split()
new_ind

['CA', 'NY', 'OR', 'LA', 'CO']

In [89]:
df['States']=new_ind

In [92]:
df=df.set_index('States')

In [93]:
df

V         W         X         Y         Z
States                                                  
CA      2.706850  0.628133  0.907969  0.503826  1.536102
NY      0.651118 -0.319318 -0.848077  0.605965 -1.167395
OR     -2.018168  0.740122  0.528813 -0.589001  1.268936
LA      0.188695 -0.758872 -0.933237  0.955057 -1.692109
CO      0.190794  1.978757  2.605967  0.683509  4.584725

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, CA to CO
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V       5 non-null      float64
 1   W       5 non-null      float64
 2   X       5 non-null      float64
 3   Y       5 non-null      float64
 4   Z       5 non-null      float64
dtypes: float64(5)
memory usage: 412.0+ bytes


In [96]:
df.describe()

V         W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871  0.906052
std    1.681131  1.061385  1.454516  0.594708  2.505539
min   -2.018168 -0.758872 -0.933237 -0.589001 -1.692109
25%    0.188695 -0.319318 -0.848077  0.503826 -1.167395
50%    0.190794  0.628133  0.528813  0.605965  1.268936
75%    0.651118  0.740122  0.907969  0.683509  1.536102
max    2.706850  1.978757  2.605967  0.955057  4.584725

In [101]:
ser_w=df['W']>0
sum(ser_w)

3

In [111]:
df=pd.DataFrame({'col1':[1,np.nan,3,4],'col2':[444,np.nan,np.nan,444],'col3':[56,80,np.nan,49]})
df

col1   col2  col3
0   1.0  444.0  56.0
1   NaN    NaN  80.0
2   3.0    NaN   NaN
3   4.0  444.0  49.0

In [112]:
df.dropna()

col1   col2  col3
0   1.0  444.0  56.0
3   4.0  444.0  49.0

In [113]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [114]:
df.dropna(thresh=2)

col1   col2  col3
0   1.0  444.0  56.0
3   4.0  444.0  49.0

In [115]:
df.fillna(df.mean())

col1   col2       col3
0  1.000000  444.0  56.000000
1  2.666667  444.0  80.000000
2  3.000000  444.0  61.666667
3  4.000000  444.0  49.000000

In [116]:
df['col1'].fillna(value=df['col1'].mean())

0    1.000000
1    2.666667
2    3.000000
3    4.000000
Name: col1, dtype: float64

In [117]:
data ={'Company':['GOGG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}
df=pd.DataFrame(data)
df

Company   Person  Sales
0    GOGG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350