<a href="https://colab.research.google.com/github/Ayush-hm/AI-Toolbox/blob/main/Time_Series_Forecasting_using_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

In [1]:
import numpy as np

In [2]:
list=[1,2,3,4]
np.array(list)

array([1, 2, 3, 4])

In [6]:
list =[[1,2,3],[4,5,6],[7,8,9]]
matrix=np.array(list)

In [12]:
print(np.arange(0,10))
print(np.arange(0,10,2))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [19]:
print(np.zeros(5))
print(np.ones(5))
print(np.zeros((3,2)))
print(np.ones((2,3)))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
print(np.ones((4,5)))
print(np.ones((4,5)) + 3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]


In [29]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.random.rand(5,6)

array([[0.90780221, 0.21999704, 0.41068226, 0.18991251, 0.22178807,
        0.9438466 ],
       [0.80021013, 0.13201797, 0.56081899, 0.43644436, 0.77413168,
        0.43438319],
       [0.61327306, 0.27813704, 0.45997327, 0.47746569, 0.86809331,
        0.60263035],
       [0.18356856, 0.94262149, 0.58180739, 0.10472018, 0.626559  ,
        0.87539759],
       [0.56701177, 0.81692005, 0.42581148, 0.07866723, 0.84816923,
        0.27858827]])

In [44]:
np.random.logseries(0.5, 4)

array([1, 2, 2, 1])

In [51]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [55]:
arr=np.arange(25)
rarr=np.random.randint(0,50,10)
print(arr)
print(rarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[36 23 17  4 41 12 49  1  8 20]


In [57]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
print(rarr.max())
print(rarr.min())
print("index of max number",rarr.argmax())
print("index of min number",rarr.argmin())

49
1
index of max number 6
index of min number 7


In [61]:
rarr.dtype

dtype('int64')

In [62]:
arr=np.arange(0,11)
print(arr[1:5])
print(arr[:5])
print(arr[5:])

[1 2 3 4]
[0 1 2 3 4]
[ 5  6  7  8  9 10]


In [63]:
arr + 200

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210])

In [64]:
arr / 3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ,
       3.33333333])

In [69]:
slice_arr=arr[0:6]
slice_arr[:]=10
slice_arr

array([10, 10, 10, 10, 10, 10])

In [70]:
arr_copy=arr.copy()
arr_copy[:]=40
arr_copy

array([40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40])

In [71]:
arr

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [82]:
arr_2d=np.array([[10,22,33],[43,56,65],[72,83,90]])
print(arr_2d)
print(arr_2d[0][1])
print(arr_2d[2,2])

[[10 22 33]
 [43 56 65]
 [72 83 90]]
22
90


In [84]:
slice_2d=arr_2d[:2,0:]
slice_2d

array([[10, 22, 33],
       [43, 56, 65]])

In [87]:
arr=np.arange(1,11)
bool_arr=arr > 5
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [95]:
arr[arr>=5]

array([ 5,  6,  7,  8,  9, 10])

In [96]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [97]:
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [98]:
arr // 2


array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [99]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [100]:
(arr + 4)/2

array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ])

In [104]:
arr/0

/tmp/ipython-input-4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [107]:
arr*(arr**2)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [108]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [109]:
np.cbrt(arr)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382, 2.15443469])

In [110]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [113]:
arr=np.sin(arr)

In [115]:
np.abs(arr)

array([0.84147098, 0.90929743, 0.14112001, 0.7568025 , 0.95892427,
       0.2794155 , 0.6569866 , 0.98935825, 0.41211849, 0.54402111])

In [116]:
arr.sum()

np.float64(1.4111883712180104)

In [117]:
arr.mean()

np.float64(0.14111883712180104)

In [118]:
arr.max()

np.float64(0.9893582466233818)

In [124]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d.sum(axis=1)) #row
print(arr_2d.sum(axis=0)) #column

[ 6 15 24]
[12 15 18]


**Pandas**